default: &defaults
  parallelism: 1
  docker:
    - image: loadimpact/k6:latest

run_load_tests: &run_load_tests
  run:
    name: Running Load Tests Using K6
    command: |
      k6 run tests/test.js

version: 2
jobs:
  load_tests:
    <<: *defaults
    steps:
      - checkout
      - *run_load_tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - load_tests

