default: &defaults
  parallelism: 1
  docker:
    - image: ubuntu:latest

setup: &setup
  run:
    name: Installing aws cli and setting it up
    command: |
      chmod 777 setup.sh
      sh setup.sh

authorize_circleci_through_firewall: &authorize_circleci_through_firewall
  run:
    name: Adding firewall rule to allow circleci through aws security group
    command: |
      chmod 777 permit.sh
      sh permit.sh

revoke_circleci_through_firewall: &revoke_circleci_through_firewall
  run:
    name: Remove firewall rule to deny circleci aws security group access
    command: |
      chmod 777 revoke.sh
      sh revoke.sh

k6_performance_tests: &k6_performance_tests
  run:
    name: Running Load Tests Using K6
    command: |
      k6 cloud tests/cloud-test.js

version: 2
jobs:
  run_perfomance_tests:
    <<: *defaults
    steps:
      - checkout
      # - *login_loadimpact
      - *k6_performance_tests

  setup_and_authorize:
    <<: *defaults
    steps:
      - checkout
      - *setup
      - *authorize_circleci_through_firewall

  revoke:
    <<: *defaults
    steps:
      - checkout
      - *revoke_circleci_through_firewall


workflows:
  version: 2
  build-workflow:
    jobs:
      - setup_and_authorize
      - run_perfomance_tests:
          requires:
            - setup_and_authorize
      - revoke:
          requires:
            - run_perfomance_tests
